ecryptfs: Guard SDP-related variables
The compiler returned these errors/warnings when `CONFIG_SDP` is
disabled:

  ../fs/ecryptfs/file.c: In function 'ecryptfs_unlocked_ioctl':
  ../fs/ecryptfs/file.c:728:10: error: unused variable 'sdp_rc' [-Werror=unused-variable]
       long sdp_rc = -ENOTTY;
            ^
  ../fs/ecryptfs/file.c: In function 'ecryptfs_compat_ioctl':
  ../fs/ecryptfs/file.c:800:10: error: unused variable 'sdp_rc' [-Werror=unused-variable]
       long sdp_rc = -ENOIOCTLCMD;

Guard `sdp_rc` variables so that those will be initialized only if SDP
is enabled.

Signed-off-by: Hendra Manudinata <manoedinata@gmail.com>